### ISSUE TITLE
Cannot read property 'newUrl' of undefined

### ISSUE THREAD

**Issue by gateway** [dtrungtin/actor-airbnb-scraper#15]
Input:

```
{
  "locationQuery": "Tahoe City, California",
  "simple": true,
  "includeReviews": false,
  "includeCalendar": false,
  "currency": "ADP",
  "proxyConfiguration": {
    "useApifyProxy": false
  },
  "maxListings": 0,
  "maxConcurrency": 50,
  "limitPoints": 100,
  "timeoutMs": 60000,
  "debugLog": true,
  "maxReviews": 1000,
  "minPrice": 0,
  "maxPrice": 100000
}
```

Output and Debug from APIFY

```
2021-03-22T16:34:12.524Z   TypeError: Cannot read property 'newUrl' of undefined
2021-03-22T16:34:12.525Z       at getData (/usr/src/app/src/index.js:60:33)
2021-03-22T16:34:12.525Z       at /usr/src/app/src/index.js:97:16
2021-03-22T16:34:12.526Z       at getSearchLocation (/usr/src/app/src/tools.js:72:24)
2021-03-22T16:34:12.526Z       at /usr/src/app/src/index.js:132:33
2021-03-22T16:34:12.527Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-22T16:34:12.527Z       at async run (/usr/src/app/node_modules/apify/build/actor.js:194:13)
2021-03-22T16:34:12.531Z npm 
```

I'm just looking for data in certain towns.. 

Thoughts?

**Comment by metalwarrior665** [comment]
Just a bad error for setting `"useApifyProxy": false`. Set it to `true` please
